### ISSUE TITLE
problems with wmake

### ISSUE THREAD

**Issue by eliBiagioli** [mintgen/shallowFoam#1]
Dear Florian Mintgen, 

   I am  a PhD student in matemathic and I am very interested in your solver! 

I have downloaded it on my pc and copied the folder into applications/solvers/incompressible, so it is together with shallowWaterFoam. Then I moved inside shallowFoam and tried to create the executeble with "wmake", but I have had these problems:

In file included from shallowFoam.C:50:0:
/opt/openfoam5/src/finiteVolume/lnInclude/readTimeControls.H: In function ‘int main(int, char**)’:
/opt/openfoam5/src/finiteVolume/lnInclude/readTimeControls.H:32:1: error: ‘adjustTimeStep’ was not declared in this scope
 adjustTimeStep =
 ^
/opt/openfoam5/src/finiteVolume/lnInclude/readTimeControls.H:35:1: error: ‘maxCo’ was not declared in this scope
 maxCo =
 ^
/opt/openfoam5/src/finiteVolume/lnInclude/readTimeControls.H:38:1: error: ‘maxDeltaT’ was not declared in this scope
 maxDeltaT =
 ^
In file included from shallowFoam.C:88:0:
zeroGradientWetDry.H:40:50: error: binding ‘const Foam::Field<Foam::Vector<double> >’ to reference of type ‘Foam::vectorField& {aka Foam::Field<Foam::Vector<double> >&}’ discards qualifiers
 vectorField& gradgSpHfi = gradgSpHf.internalField();
                                                  ^
/opt/openfoam5/wmake/rules/General/transform:25: recipe for target 'Make/linux64GccDPInt32Opt/shallowFoam.o' failed
make: *** [Make/linux64GccDPInt32Opt/shallowFoam.o] Error 1

Since I really wish to use your solver, I would like to understand how to solve these problems, could you help me, please?

I am quite new in OpenFOAM. Although I menage quite well  to deal with tutorials, I have never modified (considerably) a solver.

Thank you for your attenction

Your sincerely

Elisa Biagioli

**Comment by mintgen** [comment]
Dear Elisa,

Sorry for the late reply, I have not been visiting github very often recently, so I just saw your message. Can you please tell me what version of OpenFOAM you are using?

Best regards,
Florian

**Comment by saiful2k9** [comment]
Dear Florian Mintgen,

My name is Saiful Islam and I am doing my masters at TUM. I am trying to use your solver but its not working in OpenFOAM 5.1 version. Could yoy please tell me, how can I fix this problem?

Best Regards

**Comment by HaochenCFD** [comment]
Hi,
I compile the 4.1 branches with OF 5.0 without any problem.
Thanks,
Rdf

**Comment by SHAILJA0** [comment]
Hii Mintgen
I am trying to install shallowFoam solver in OpenFoam-5 but getting following eror

In file included from shallowFoam.C:100:0:
zeroGradientWetDry.H: In function ‘int main(int, char**)’:
zeroGradientWetDry.H:40:50: error: binding reference of type ‘Foam::vectorField& {aka Foam::Field<Foam::Vector<double> >&}’ to ‘const Foam::Field<Foam::Vector<double> >’ discards qualifiers
 vectorField& gradgSpHfi = gradgSpHf.internalField();

Any idea to solve this ?

**Comment by SHAILJA0** [comment]
I got the solution by changing in zeroGradientWetDry.H file following
vectorField& gradgSpHfi = gradgSpHf.internalField();

to 

vectorField& gradgSpHfi = gradgSpHf.ref();

It worked with some warnings.
